### ISSUE TITLE
generate errors

### ISSUE THREAD

**Issue by kaiyu-tang** [amirbar/rnn.wgan#10]
HI, I use the default setting for curriculum_training, than use 
--GENERATOR_MODEL=Generator_RNN_CL_VL_TH --DISCRIMINATOR_MODEL=Discriminator_RNN --ckpt_path=F:\NLP\rnn-wgan\logs\Generator_RNN_CL_VL_TH-Discriminator_RNN-50-10-512-512-1510731157.353556-\checkpoint 
for generate script parameters. While error happens in model.py.
  File "F:\NLP\rnn-wgan\model.py", line 52, in Generator_RNN_CL_VL_TH
    cells.append(rnn_cell(num_neurons))
TypeError: 'NoneType' object is not callable
Could you plz give me some suggestions?

**Comment by ofirpress** [comment]
Are you using Tensorflow-gpu version 1.1?
We know this code works on 1.1, on later versions it might not work.

**Comment by sunsidazzz** [comment]
I got the same error and I am using tf1.1, do you know what happened there?

**Comment by ofirpress** [comment]
Maybe the ckpt_path is incorrect?

**Comment by ofirpress** [comment]
Make sure your ckpt_path looks like:
--CKPT_PATH=./logs/Generator_RNN_CL_VL_TH-Discriminator_RNN-50-10-512-512-1516543503.49-/checkpoint/seq-5/ckp
(and not like the one you used.)

See the updated README for more details. The previous README may have been misleading.
