### ISSUE TITLE
How long does this take to train with the default hyperparameters?

### ISSUE THREAD

**Issue by edwhu** [amirbar/rnn.wgan#11]
I would like to know what hardware you used and its approximate training time.

**Comment by amirbar** [comment]
I don't remember the exact training time. Matter of few days, I think, on a single K80. 
When you reach a sequence length of 13-14 you can start experimenting with generating long sequences in an ok quality.

**Comment by edwhu** [comment]
Thanks for the info!

**Comment by edwhu** [comment]
Hello,
Just an inquiry for further information.
Not sure if my training time matches what you said.  I'm getting around 20 days of training.
 Right now, for me, with a GTX1070, it seems to increase linearly by one hour per training phase, which makes sense because of the curriculum process. So I calculate it would take around 20 days to complete the entire curriculum training process. 
I am trying the FGAN objective with 2 Generator iterations and 2 Critic iterations per step. 
Is this length in training time expected? Or perhaps I am doing something wrong.

**Comment by edwhu** [comment]
@NickShahML could you tell me how long it took for the FGAN to train using curriculum training of 32 stages? And what hardware you used?

**Comment by ofirpress** [comment]
We didn't train/use the FGAN in the paper so I cant really comment on that.
For the Improved WGAN CL+VL+TH model, I also don't remember the exact training time, but I think it was around 12 days to completely train the model, so 20 days doesn't sound wrong.

**Comment by edwhu** [comment]
Thank you for the info.
