### ISSUE TITLE
Is there a way to generate variable length text?

### ISSUE THREAD

**Issue by AlexG31** [amirbar/rnn.wgan#12]
It seems current code can only work with fixed length text generation, then generator and discriminator are trained for fixed length input/output. I'm wondering is there a way to generate variable length text?

**Comment by amirbar** [comment]
The generator/discriminator are trained for a *configurable* fixed length.
In inference, you can define the exact sequence length you want to generate in the file generate.py. 

i.e to generate a sequence of length k:

python generate.py --CKPT_PATH=/path/to/checkpoint --DISC_GRU_LAYERS=2 --GEN_GRU_LAYERS=2 --END_SEQ=k
