### ISSUE TITLE
Adapt code for Lyrics Generation

### ISSUE THREAD

**Issue by simonefrancia** [amirbar/rnn.wgan#13]
Hi,
thanks for the repo, I think it's an original idea to apply GANs.

I would ask for some advice for adapting this code for lyrics. I have large availability of lyrics, but I don't have an idea to adapt the code for my task. 
Trying to be more clear: I would create a GAN that, at the end of the training steps, is able to generate lyrics (general format lyrics, not specified on particular artist) and at the same time use the trained discriminator (after training) to recognize lyrics that doesn't match format ( sort of spam detection).

Do you think it's a good idea? Could you suggest something in this way? 
Thanks

Simone

**Comment by ofirpress** [comment]
Thanks a lot for you interest in our work. 

If you just replace the training data we currently use with song lyrics, you could get what you want. 

But, please note that this is a research project that we published more than a year ago to show the viability of a pure GAN approach to text generation. You can see some samples in our paper, and you will notice that the generated text is not very coherent when you read more then three words at a time. 

Even today, GAN approaches to text generation have not beaten MLE models. Therefor I would recommend you try other approaches to solve your problem before resorting to GANs.

**Comment by simonefrancia** [comment]
Thanks for response. 
Could you suggest some approaches? 
Do you think that this approach can be correct https://github.com/CR-Gjx/LeakGAN?

Thanks
