### ISSUE TITLE
WGAN-GP vs. FisherGAN on langauge generation in practice

### ISSUE THREAD

**Issue by lifelongeek** [amirbar/rnn.wgan#7]
Could you share your experience of WGAN-GP vs. FisherGAN on learning language generator?
Conceptually, I think 'sampling along the line between real sequence vs. generated sequence' of WGAN-GP sounds not natural for sequence because they can be different length. But I want to know which method works well in practice.

cf) If this is not appropriate topic for Issues, I will delete this post.

**Comment by ofirpress** [comment]
The FisherGAN implementation is an experimental and external contribution to the project. It didn't appear on the paper and we haven't seen it perform better than the WGAN-GP model yet.

About your question: You are correct that in the current implementation, when we sample a along the line between a real and generated sequence, the real and the generated sequences could be of different lengths. We did not try constraining the training procedure to make sure that the real and generated sequences are of the same length. Doing this could improve the training process, but the only way to know for sure would be to actually test this.

If you have any more questions, feel free to contact me or one of the other authors.
